### ISSUE TITLE
Paper - report for semester A

### ISSUE THREAD

**Issue by KobyBrandes** [TechnionYearlyProject/TheDoors#113]
1. Introduction - Elyasaf
2. RElated work - Aviad
3. Design and implementation - Ilana
4. Evaluation - Yarin
5. Abstract+conclusions+refrences - Koby

All should send their part to me no later than friday, 30 March at 11am.

**Comment by KobyBrandes** [comment]
5. Abstract+conclusions+refrences+ organize in the proper structure
time estimation: 4 hrs.

**Comment by elyasaf-boim** [comment]
1. Introduction .
time estimation: 5 hrs.

**Comment by yrnoz** [comment]
4. Evaluation.
Time estimation: 5 hrs.

**Comment by aviadRozenknof** [comment]
2. Related Work
time estimation: 4 hrs

**Comment by ilana1115** [comment]
3. Design and Imlantation
time estimation: 6 hrs
