### ISSUE TITLE
Friends table refactoring

### ISSUE THREAD

**Issue by aviadRozenknof** [TechnionYearlyProject/TheDoors#146]
make a comfortable api for working with the db

**Comment by elyasaf-boim** [comment]
estimate time for #143  #144 #145 #146 : 13 hours

**Comment by elyasaf-boim** [comment]
![image](https://user-images.githubusercontent.com/33027226/39562434-4acdf0a0-4eb4-11e8-9140-567f0bcb5fd0.png)

add table for facilities

**Comment by elyasaf-boim** [comment]
![image](https://user-images.githubusercontent.com/33027226/39673666-1fd6aa12-5149-11e8-84b3-ed60e49794a1.png)


users ---> friends:  every user have friends in the friends table

users ---> facilities: every user is a worker in a company, so the user have a list of facilities of the company

users ---> orders: every user can to create an order, so the orders of this users saved in this table

users ---> schedules: every order translated into user schedules at last, so this table save the schedule of every user.

rooms <---> schedules: if we want to know the schedule of this rooms, when it full or empty etc

rooms <---> facilities: every room is part of facility.

schedules <---> order: every meeting on the schedule table is related to order object that match it
