### ISSUE TITLE
Azure and Mongo

### ISSUE THREAD

**Issue by KobyBrandes** [TechnionYearlyProject/TheDoors#148]

**Comment by KobyBrandes** [comment]
How to integrate azure with mongoDB.
Estimated time: 10 hrs.
Actual time:

**Comment by KobyBrandes** [comment]
Conclusions:
mongo in azure is very inconvinient, we need a virtual machine and the database should run there and we need to write API.
However, azureSQL gives us an API so in the weekly meeting we should disscus tranforming our db to SQL.

**Comment by yrnoz** [comment]
so finally the web app is online
actual work time: ~12 hours (a lot of trial and error until I managed to properly configure our files)
URL: https://thedoors.azurewebsites.net/
