### ISSUE TITLE
Analytics Tests

### ISSUE THREAD

**Issue by yrnoz** [TechnionYearlyProject/TheDoors#160]

**Comment by ilana1115** [comment]
Time estimation: 2 hours

**Comment by KobyBrandes** [comment]
I would like to test the implementation of the analytics section and to expand it because it seems to be insufficient.
I need to include the data about the algorithm Ilana does.

**Comment by KobyBrandes** [comment]
During the test I found some bugs that their description can be found in the commit that fixed them.
I encountred a significant problem with the git during this job and therefore it took too much time (making it at least twice)
