### ISSUE TITLE
Weekly Log for Ilana Levitan

### ISSUE THREAD

**Issue by TomPalny** [TechnionYearlyProject/TheDoors#2]
This issue is meant to help in monitoring assignments in the project, progress, and volume of work.

Write here current tasks you are doing , as well as past work that is finished.

Whenever possible, please include an issue number that relates to the task you are writing.

Make use of the bulleted list as a way to organize things.

Have a great semester!

**Comment by ilana1115** [comment]
* Finding Bugs in the feature #13

**Comment by ilana1115** [comment]
Week 4:
* Doing presentation to the 24/12

**Comment by ilana1115** [comment]
Beginning of Sprint 2: 
Week 9:
- doing #44 . delete schedule

**Comment by ilana1115** [comment]
Week 10:
* doing #69

**Comment by ilana1115** [comment]
Week 11:
* Fix  bugs in #69 
* Doing tests to #70

**Comment by ilana1115** [comment]
Week 12 (last week): did a lot of work:
* k
