### ISSUE TITLE
user: receive room recommendation by hour and other constraints

### ISSUE THREAD

**Issue by yrnoz** [TechnionYearlyProject/TheDoors#21]
employee would have the ability to receive room recommendations according to his needs (hour, number of minimum room capacity and more)

**Comment by elyasaf-boim** [comment]
commits for room rec:

873f4f7e2958fa2c354b5bf5e6ada02e45abba12
7ca1a4f0ad9ac300f5e48df5afe0ea91f88a0875
ca10a79483f717883415365779530f20733df0e5
0b41b3dd436c8e8d6425c537055f46b6786641ba
6773a7b0e000fd2b3c365fa3a524dfe3254ae595
2b623fec188d818fc9da2782e9e32cc24bbb081f

**Comment by KobyBrandes** [comment]
92089ad
808ff01
