### ISSUE TITLE
Weekly Log for Yarin Ozery

### ISSUE THREAD

**Issue by TomPalny** [TechnionYearlyProject/TheDoors#3]
This issue is meant to help in monitoring assignments in the project, progress, and volume of work.

Write here current tasks you are doing , as well as past work that is finished.

Whenever possible, please include an issue number that relates to the task you are writing.

Make use of the bulleted list as a way to organize things.

Have a great semester!

**Comment by yrnoz** [comment]
# Week 7:
- Fixed a bug (room and employee ids were considered as integers instead of strings)
- Wrote tests for importing employee and rooms details (Issue #39 ) and validated they are passing
- TODO: Write tests for exporting employees and rooms details

**Comment by yrnoz** [comment]
Week 8 (+ Hanuka):
- Started working towards deploying our DB to the cloud:
- Learned how to work with Heroku (went over a toturial in their website).
- Learned how to work with mLab (a cloud service for hosting MongoDB).

**Comment by yrnoz** [comment]
# Week 9 :
- Added feature for adding employees + a small test to make sure it's working (whoever tests the friend network feature still needs to write tests for it of course), as required in issue #46 
- Fixed a bug where exported file of employees wouldn't include friend list (issue #43)
- Added documentation (rooms/employees exporting functions)

**Comment by yrnoz** [comment]
# Week 10:
* Added support for location sharing of  employee with his friends (Issue #47), as well as small tests for it.
* Fixed ManageDB bugs that caused the build to fail.
* Added build badge to the repository

**Comment by yrnoz** [comment]
# Week 11:
* Wrote method that checks if there are friends of given employee in a specific room (Issue #82)

**Comment by yrnoz** [comment]
# Weeks 12 + 13:
* Fixed a small problem where the "go back" buttons didn't appear in edit DB's screens due to bad positioning (issue #78)
* Added support for adding weekly schedule (including with other employees, affecting their schedule as well), Issues #97 and #98
* Designed GUI for add weekly schedule screen (#97).
* Updated a lot of old code to work with Flask (#98).
