### ISSUE TITLE
Weekly Log for Koby Brandes

### ISSUE THREAD

**Issue by TomPalny** [TechnionYearlyProject/TheDoors#4]
This issue is meant to help in monitoring assignments in the project, progress, and volume of work.

Write here current tasks you are doing , as well as past work that is finished.

Whenever possible, please include an issue number that relates to the task you are writing.

Make use of the bulleted list as a way to organize things.

Have a great semester!

**Comment by KobyBrandes** [comment]
week 7:
* installing pytest and understanding how it works.
* Adding functions to mangaging the DB.
* Testing RoomRecomendation. #21 
* Testing Ilana and Yarin's code - add_weekly_schedule #41

**Comment by KobyBrandes** [comment]
week 8 + Hanuka:
* Finish testing Ilana and Yarin's feature #41.
* Fixing some bugs in Room-Recommendation which rised in Stav and Aviad's testing #21 .
* Beginning with the feature of reccomendation according to friends .
* Mockup with Stav and Elyasaf.
* Searching for material about GUI.

**Comment by KobyBrandes** [comment]
week 9:
* Adding constraints to room reccomendation: constraint by number of floor and constraint by capaicty of the room #55 .
* Learning how to work with Bootstrap and making an example #53 .

**Comment by KobyBrandes** [comment]
week 10:
* Learning how to work with Django and making their guide (in their website) #67 .
* Adding support in password to the system #71 .

**Comment by KobyBrandes** [comment]
week 11:
* Manager Interface #59 .
* User Interface #60 .
* Editing pages #79 .
* Trying to implement the system with django (3 dufferent guides) #83 .
* Improving the password logic #85 .
* Trying to implement thw system with flask #86 .
* JQuery material.

**Comment by KobyBrandes** [comment]
week  12:
* Trying to implement the system with flask #86 .
* Dealing with problem with bootstrap in flask #92 
* Making the room search/update/delete pages with their logic and concatenation to the DB. #95 
* Beginning room reccomendation page with its logic and concatenation to the DB. #100 
* Designing, improving the GUI after using Flask. #87 #99 
* Presentation: editing and explaining the problem we had with django.
