### ISSUE TITLE
Weekly Log for Aviad Rozenknof

### ISSUE THREAD

**Issue by TomPalny** [TechnionYearlyProject/TheDoors#6]
This issue is meant to help in monitoring assignments in the project, progress, and volume of work.

Write here current tasks you are doing , as well as past work that is finished.

Whenever possible, please include an issue number that relates to the task you are writing.

Make use of the bulleted list as a way to organize things.

Have a great semester!

**Comment by aviadRozenknof** [comment]
week 6:
*adding function to DB for issue #13 
*write some tests for the function i write
*write function of adding employee to a room in specific date and hour
*write the main function of issue #13 that gets csv file and not list of schedule items.
*work on the Test Plan document

**Comment by aviadRozenknof** [comment]
**Week 7:**
* installing pytest and learn about it.
* fix some bugs in room recommendation issue #21 
* write functions for export rooms/employees from the DB #43 
*fix bugs in function of adding weekly schedule from csv file #13 
* discuss with Stav about how to test the room recommendation feature #42

**Comment by aviadRozenknof** [comment]
**week 8:**
* fix add weekly schedule feature #13 
* fix some bugs in the code
* write tests for room recommendation feature #21 
* discuss about the presentaion for sprint 1

**Comment by aviadRozenknof** [comment]
**week 9:**
* work on the presentation for sprint 1
* open new issues for sprint 2
* discuss with stav about the simulation engine we need to work on
* add function of import rooms for the simulation engine #50 
* add function of create random employees for the simulation #49

**Comment by aviadRozenknof** [comment]
**week 10:**
* add function of copy the existing employees to the simulation.
* add functions of get average friends and minimum permissiom access for the manager 
* add function of assigning employees to rooms in the simulation engine.
* start to learn about using NFC in our project in the website: http://nfcpy.readthedocs.io/en/latest/

**Comment by aviadRozenknof** [comment]
**week 11:**
* write the main function of the simulation #52 
* write function of assign employees to random rooms for the simulation #52

**Comment by aviadRozenknof** [comment]
**week 12+13:**
* learn flask by Elyasaf #86
* work on change room recommendation to work with flask #100 
* finish the main function of the simulation engine #52 
* write tests for the simulation engine #94 
* learn to work with tables in flask and python #90 
* fix codecov problems for the project
* write and design the end semester presentation
