### ISSUE TITLE
Flask guide

### ISSUE THREAD

**Issue by KobyBrandes** [TechnionYearlyProject/TheDoors#86]
Django makes a lot of problems, trying Flask

**Comment by KobyBrandes** [comment]
Starting with this guide:
https://flask-pymongo.readthedocs.io/en/latest/

**Comment by elyasaf-boim** [comment]
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iii-web-forms

**Comment by KobyBrandes** [comment]
FLask with pyMongo:

http://flask-appbuilder.readthedocs.io/en/latest/quickhowto_mongo.html
